cover: handson/DSC00636.jpg
sub_title: 
theme: light
title: Saas-Fee 2022

sections:

- type: full-picture
  fixed: true
  image: contrib/2022_01_25__Saas-Fee_Langflueh_Wide_smaller.png
  text:
    title: Saas-Fee 2022 
    sub_title: 23 - 29 January 2022 
    

- type: pictures-group
  fill_with: gallery/mountain/
  images:
  - - contrib/2022_01_25__Saas-Fee_Langflueh_Town.png
    - contrib/2022_01_25__Saas-Fee_Langflueh_Wide.png
    - mountain/20220126_154812_46.11367_7.92987.jpg
    - mountain/20220126_155015_46.11367_7.92987.jpg


  - - contrib/IMG_8506.jpg
    - contrib/IMG_8510.jpg
    - contrib/IMG_8486.jpg

  - - contrib/IMG_8533.jpg
    - contrib/IMG_8544.jpg

  - - mountain/image.png
    - mountain/DSC00513_01.jpg
    - mountain/DSC00547_01.jpg
    - mountain/DSC00526.jpg

  # pair
  - - mountain/DSC00550.jpg
    - mountain/DSC00629.jpg
 
  # ice
  - - mountain/DSC00522_01.jpg # zoom haze
    - contrib/IMG_8547.jpg
    - mountain/DSC00529_01.jpg
    - mountain/DSC00531_01.jpg
  - - mountain/DSC00531.jpg
    - mountain/DSC00514_01.jpg
    - mountain/DSC00534.jpg
      

      #- mountain/9C7250B1-9F0C-4861-8116-CA78375600CB_1_105_c.jpeg

  # night
  - - contrib/IMG_8553.jpg
    - mountain/DSC00630.jpg
    - contrib/IMG_8463.jpg
    - mountain/DSC00619.jpg
    - mountain/DSC00628.jpg
    - mountain/DSC00620.jpg

  - - contrib/IMG_8559.jpg
    - contrib/IMG_8567.jpg
    - contrib/IMG_8576.jpg
    - contrib/IMG_8578.jpg
    - contrib/IMG_8584.jpg


- type: full-picture
  fixed: true
  image: handson/20220125_175012.jpg
  text:
    title: the learning


- type: pictures-group
  images:
  - - lectures/20220126_110803.jpg
    - handson/20220126_165841_01.jpg
    - handson/20220127_084154.jpg
    - handson/20220127_084204.jpg
    - handson/20220127_084218.jpg
  - - handson/20220127_104429.jpg
    - handson/20220127_153605.jpg
    - handson/20220128_080419.jpg
    - handson/20220128_104000.jpg
    - handson/DSC00552_01.jpg
  - - handson/DSC00553.jpg
    - handson/DSC00555.jpg
    - handson/DSC00556.jpg
    - handson/DSC00557.jpg
    - handson/DSC00559.jpg
    - handson/DSC00561.jpg
    - handson/DSC00562.jpg
    - handson/DSC00563.jpg
    - handson/DSC00564.jpg
    - handson/DSC00567.jpg
  - - handson/DSC00570.jpg
    - handson/DSC00574.jpg
    - handson/DSC00576.jpg
    - handson/DSC00577.jpg
    - handson/DSC00579.jpg
    - handson/DSC00581.jpg
    - handson/DSC00582.jpg
    - handson/DSC00583.jpg
    - handson/DSC00584.jpg
  - - handson/DSC00585.jpg
    - handson/DSC00586.jpg
    - handson/DSC00590.jpg
    - handson/DSC00592.jpg
    - handson/DSC00593.jpg
    - handson/DSC00595.jpg
    - handson/DSC00597.jpg
    - handson/DSC00599.jpg
    - handson/DSC00600.jpg
  - - handson/DSC00601.jpg
    - handson/DSC00602.jpg
    - handson/DSC00603.jpg
    - handson/DSC00604.jpg
    - handson/DSC00605.jpg
    - handson/DSC00606.jpg
    - handson/DSC00607.jpg
    - handson/DSC00611.jpg
    - handson/DSC00614.jpg

- fixed: true
  image: cat/DSC00612.jpg
  text:
    sub_title: gracious host
    title: the Cat
  type: full-picture

- type: pictures-group
  images:
  - - handson/20220125_173838.jpg
    - contrib/2022-01-27_10.15.09.jpg
    - cat/DSC00612.jpg
    - DSC00608.jpg
    - DSC00609.jpg
    - cat/IMG_20220127_105257_1.jpg
    - contrib/IMG_8469.jpg

- fixed: true
  image: skiing/GH020073-finaldownhill-f014570.png
  text:
    sub_title: Some impressing skiing from Ilya
    title: the Skiing
  type: full-picture
- images:
  - - skiing/GH020073-finaldownhill-f014570.png
    - contrib/20220127_175820.jpg
    - contrib/20220127_175929.jpg
    - contrib/GH010073_1643298345557.JPG
  - - name: skiing/starting.mp4
      type: video
    - name: skiing/letsski.mp4
      type: video
    - name: skiing/aerodanamicissues.mp4
      type: video
    - name: skiing/godownhere.mp4
      type: video
  type: pictures-group

- images:
  - - handson/DSC00636.jpg
  type: pictures-group


- fixed: false
  image: DSC00727_01.jpg
  text:
    date: 2022-01-28
    sub_title: See you!
    title: The End
  type: full-picture

- type: paragraph
  text: |
      
      <div width="100%" align="center"><a href="https://www.astro.unige.ch/saasfee2022">Visit school site for more info!</a>
      <br>
      <br>
      <small>Photos contributed by mutliple participants.<br> Please <a href="https://www.astro.unige.ch/saasfee2022/content/contact">contact the conference organizers</a> with any concerns or questions.</small>
      </div>
